# **Início**

  Nesse *notebook* trabalhei na parte de conhecimento, limpeza e refatoração dos dados, para deixar-los mais próximos da proposta de análise dessa *EDA*.

 Fato divertido: Em projetos de análise, estima-se que 80% do tempo seja gasto apenas transformando e limpando a base de dados, e os 20% restantes seriam tirar os *insights*, plotagem e ajustes finais na parte visual.

 Apesar de se tratar de uma base de dados do governo de Washington, existem inconsistências (Muitas vezes dados que não existem informação oficial) e dados que pouco interessam a nossa *EDA*, pois ela tem foco em dados como autonomia, *marketshare* e evolução da tecnologia, logo informações como o número do chassi, id da pesquisa, código postal e outras informações que não casam com a ideia do projeto foram removidas.

## Parte I - Importações e carregamento dos dados
 A seção de códigos abaixo se trata do início do início, nada demais, importação de bibliotecas, carregamento do arquivo CSV com os dados e transformação para um Dataframe do pandas.

In [1]:
# Importações iniciais de bibliotecas

import pandas as pd
import numpy as np

In [2]:
# Abrindo o arquivo csv com a base de dados

df = pd.read_csv(r"C:\Users\piaze\Documents\Projetos\EDA-Carros-Eletricos-Washington\base_de_dados\Electric_Vehicle_Population_Data_20260122.csv")

df.head(10)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EB9J,Kitsap,Bainbridge Island,WA,98110.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,23.0,476462444,POINT (-122.521 47.62732),PUGET SOUND ENERGY INC,5.303509e+10
1,JN1AZ0CP2B,Kitsap,Port Orchard,WA,98367.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,26.0,279030461,POINT (-122.70348 47.52028),PUGET SOUND ENERGY INC,5.303509e+10
2,JN1AZ0CP8B,King,Bothell,WA,98011.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,1.0,232370001,POINT (-122.20563 47.76144),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
3,1G1FY6S06L,Yakima,Selah,WA,98942.0,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,15.0,264646266,POINT (-120.53145 46.65405),PACIFICORP,5.307700e+10
4,KNDCM3LD3L,King,Seattle,WA,98133.0,2020,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,32.0,154002691,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
5,KNDCS3LF9P,Thurston,Olympia,WA,98502.0,2023,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,33.0,22.0,249788311,POINT (-122.92333 47.03779),PUGET SOUND ENERGY INC,5.306701e+10
6,WAUUPBFF9G,King,Seattle,WA,98103.0,2016,AUDI,A3,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,16.0,43.0,198988891,POINT (-122.35436 47.67596),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
7,5YJ3E1EB9J,Thurston,Tumwater,WA,98512.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,22.0,115875693,POINT (-123.04078 46.94792),PUGET SOUND ENERGY INC,5.306701e+10
8,5YJSA1E20J,Kitsap,Bremerton,WA,98337.0,2018,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,249.0,26.0,261482455,POINT (-122.62749 47.565),PUGET SOUND ENERGY INC,5.303508e+10
9,1G1RD6S55H,Snohomish,Lynnwood,WA,98087.0,2017,CHEVROLET,VOLT,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,53.0,21.0,117693012,POINT (-122.27981 47.85727),PUGET SOUND ENERGY INC,5.306104e+10

## Parte II - Conhecendo os dados
 Nesta parte se encontram células rodando comandos para reconhecimento básico do *dataframe*, como a forma (Número de linhas e colunas), tipo de cada coluna além de uma rápida verificada sobre a existência de dados nulos.

In [3]:
# Entendendo os dados

df.shape

(271113, 16)

In [4]:
# Informações das colunas

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271113 entries, 0 to 271112
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         271113 non-null  object
 1   County                                             271103 non-null  object
 2   City                                               271103 non-null  object
 3   State                                              271113 non-null  object
 4   Postal Code                                        271103 non-null  float64
 5   Model Year                                         271113 non-null  int64
 6   Make                                               271113 non-null  object
 7   Model                                              271113 non-null  object
 8   Electric Vehicle Type                              271113 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  271113 non-null  object
 10  Electric Range                                     271106 non-null  float64
 11  Legislative District                               270454 non-null  float64
 12  DOL Vehicle ID                                     271113 non-null  int64
 13  Vehicle Location                                   271025 non-null  object
 14  Electric Utility                                   271103 non-null  object
 15  2020 Census Tract                                  271103 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 33.1+ MB

In [5]:
# Conhecendo os dados

df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,271103.000000,271113.000000,271106.000000,270454.000000,2.711130e+05,2.711030e+05
mean,98176.923405,2021.995068,39.885639,28.813229,2.449143e+08,5.297202e+10
std,2576.510222,3.056730,78.764355,14.898449,6.365566e+07,1.632879e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.201288e+08,5.303301e+10
50%,98133.000000,2023.000000,0.000000,32.000000,2.619548e+08,5.303303e+10
75%,98382.000000,2024.000000,33.000000,42.000000,2.781037e+08,5.305394e+10
max,99577.000000,2026.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

In [6]:
# Consultando a existência de dados nulos

df.isna().sum()

VIN (1-10)                                             0
County                                                10
City                                                  10
State                                                  0
Postal Code                                           10
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         7
Legislative District                                 659
DOL Vehicle ID                                         0
Vehicle Location                                      88
Electric Utility                                      10
2020 Census Tract                                     10
dtype: int64

## Parte III - Limpeza e tratamento de dados
 A parte mais longa do notebook. Assim como anteriormente existem comentários nas células para ajudar a explicar decisões tomadas, mas aqui tem um guia rápido delas: 

 **1 -** Removi 10 linhas com valores *NaNs*, eram informações de registro: Cidade, condado e código postal. apesar não serem essenciais para a análise futura, decidi por remover elas, pois 10 linhas em um *Dataframe* com cerca de 271 mil linhas, não é uma grande perda.

 **2 -** Removi todas as linhas que não se referiam ao estado de Washington, pois o foco da pesquisa é o estado de Washington, "perdi" cerca de mil linhas com isso, o que novamente não é muito comparado as 270 mil restantes após isso.

 **3 -** O *Dataset* usa como padrão 0.0 para carros com autonomia não registrada, optei por trocar por *NaNs*, para na análise futura, esses modelos que não tem dados apresentados, puxarem médias para baixo. A maioria dos casos se tratam de carros muito recentes, que não tem esses dados disponíveis para o governo ainda.

 **4 -** Foram removidas as colunas: localização de veiculo, distrito, vin(idendificador de chassi), código postal, 2020 census tract, estado (Visto que todos são washington) e  *DOL*(Equivalente do detran nos EUA), por serem dados irrelevantes para minha análise ou serem informações repetidas/casadas.

 **5 -** Criei a coluna idade do veículo, que é medida em anos, sendo o ano do meu projeto (2026) - o ano de fabricação do carro.

 **6 -** Diversas alterações de nomes nas células de colunas, para deixar os nomes mais curtos e intuitivos; além de valores *NaNs* para carros que não tem alternativa de combustível pesquisada.

 **7 -** Verificação de outliers pelo metódo de quartis, usando a função que criei no arquivo ferramentas.py.

 ### Q&A

 Q: Porque remover Bonneville?

 A: Se trata de a compania estatal de Washington, que tinha seu nome vinculado a outros postos de energia, logo não é uma vendedora real em casos como "BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF COWLITZ COUNTY", além de se tratar da mesma empresa.

 Q: É possível ver outliers! porque não fez nada?

 A: Ok, usando matemática "bruta", casos como um carro da ford de 1999 ser elétrico podem ser considerados uma *outlier*, mas não é algo mentiroso nem incorreto, apenas algo comum de se ver em um *Dataframe* tão diverso como esse, que possui carros híbridos e elétricos, além de modelos com mais de 20 anos de diferença.

 Q: Porque remover tantas colunas?

 A: Minha análise tem como objetivo *marketshare*, evolução da tecnologia e aspectos geograficos básicos, logo colunas como número de chassi não importam; e colunas como as cordenadas não convém com o intuito da pesquisa, apesar de serem riquissimas para outros tipos de análise.

 Q: Porque remover as 10 linhas?

 A: # Já que são apenas 10 linhas com valores NaN, perto de 270 mil linhas, removê-las não fará diferença, além disso são informações muito específicas e dificeis de encontrar, logo tranformar essas linhas não vale a pena.

In [7]:
# Removendo 10 linhas inconsistentes

df = df.dropna(subset=["City"])
df.isna().sum()

VIN (1-10)                                             0
County                                                 0
City                                                   0
State                                                  0
Postal Code                                            0
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         7
Legislative District                                 649
DOL Vehicle ID                                         0
Vehicle Location                                      78
Electric Utility                                       0
2020 Census Tract                                      0
dtype: int64

In [8]:
# Resetando o index após remover as linhas sujas

df.reset_index()

,index,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,0,5YJ3E1EB9J,Kitsap,Bainbridge Island,WA,98110.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,23.0,476462444,POINT (-122.521 47.62732),PUGET SOUND ENERGY INC,5.303509e+10
1,1,JN1AZ0CP2B,Kitsap,Port Orchard,WA,98367.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,26.0,279030461,POINT (-122.70348 47.52028),PUGET SOUND ENERGY INC,5.303509e+10
2,2,JN1AZ0CP8B,King,Bothell,WA,98011.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,1.0,232370001,POINT (-122.20563 47.76144),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
3,3,1G1FY6S06L,Yakima,Selah,WA,98942.0,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,15.0,264646266,POINT (-120.53145 46.65405),PACIFICORP,5.307700e+10
4,4,KNDCM3LD3L,King,Seattle,WA,98133.0,2020,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,32.0,154002691,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271098,271108,5YJ3E1EC8P,Snohomish,Woodinville,WA,98077.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,1.0,241530824,POINT (-122.07326 47.75425),PUGET SOUND ENERGY INC,5.306105e+10
271099,271109,7FCEHEB2XR,Skagit,Burlington,WA,98233.0,2024,RIVIAN,EDV,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,10.0,283223496,POINT (-122.33029 48.46846),PUGET SOUND ENERGY INC,5.305795e+10
271100,271110,3GPKHZRJ8R,Clark,Vancouver,WA,98682.0,2024,HONDA,PROLOGUE,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,17.0,276399231,POINT (-122.55149 45.69345),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
271101,271111,1C4JJXN6XP,Pierce,Tacoma,WA,98406.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,28.0,280031559,POINT (-122.52082 47.26887),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305306e+10
271102,271112,1C4JJXP69P,King,Seattle,WA,98107.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,36.0,276851844,POINT (-122.38591 47.67597),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10

In [9]:
# Garantindo que estamos olhando apenas para Washington e mais nenhum estado

df = df[df["State"] == "WA"]
df

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EB9J,Kitsap,Bainbridge Island,WA,98110.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,23.0,476462444,POINT (-122.521 47.62732),PUGET SOUND ENERGY INC,5.303509e+10
1,JN1AZ0CP2B,Kitsap,Port Orchard,WA,98367.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,26.0,279030461,POINT (-122.70348 47.52028),PUGET SOUND ENERGY INC,5.303509e+10
2,JN1AZ0CP8B,King,Bothell,WA,98011.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,1.0,232370001,POINT (-122.20563 47.76144),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
3,1G1FY6S06L,Yakima,Selah,WA,98942.0,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,15.0,264646266,POINT (-120.53145 46.65405),PACIFICORP,5.307700e+10
4,KNDCM3LD3L,King,Seattle,WA,98133.0,2020,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,32.0,154002691,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271108,5YJ3E1EC8P,Snohomish,Woodinville,WA,98077.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,1.0,241530824,POINT (-122.07326 47.75425),PUGET SOUND ENERGY INC,5.306105e+10
271109,7FCEHEB2XR,Skagit,Burlington,WA,98233.0,2024,RIVIAN,EDV,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,10.0,283223496,POINT (-122.33029 48.46846),PUGET SOUND ENERGY INC,5.305795e+10
271110,3GPKHZRJ8R,Clark,Vancouver,WA,98682.0,2024,HONDA,PROLOGUE,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,17.0,276399231,POINT (-122.55149 45.69345),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
271111,1C4JJXN6XP,Pierce,Tacoma,WA,98406.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,28.0,280031559,POINT (-122.52082 47.26887),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305306e+10
271112,1C4JJXP69P,King,Seattle,WA,98107.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,36.0,276851844,POINT (-122.38591 47.67597),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10

## Removendo valores zerados de autonomia

 Analisando com o *Data Wrangler* os valores de autonomia, percebe-se que muitos carros estão com valores 0, pesquisando mais a fundo, descobri que são veículos mais recentes, e que não tem sua autonomia registrada oficialmente. Além disso colunas como distrito legislativo e a localização em coordenadas também possuem valores nulos ou zerados, mas manterei os NaNs e transformarei os 0s em NaNs, pois essas colunas pouco importam para a análise.

In [10]:
# Redigindo os valores zero para NaNs

df["Electric Range"] = df["Electric Range"].replace(0, np.nan)
df["Electric Range"].isna().sum()

np.int64(170437)

## Removendo colunas irrelevantes para a análise

Irei remover as colunas de localização de veiculo, distrito, vin(idendificador de chassi), código postal, 2020 census tract, estado(Visto que todos são washington) e *DOL*(Equivalente do detran  em Washington) visto que essa EDA foca mais em mercado e não estatíticas geograficas precisas.

In [11]:
# Removendo as colunas citadas acima

cols_para_remover = ["Vehicle Location", "Legislative District", "VIN (1-10)", "Postal Code", "2020 Census Tract", "DOL Vehicle ID", "State"]
df = df.drop(columns=cols_para_remover)
df.head()

,County,City,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Electric Utility
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,PUGET SOUND ENERGY INC
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,PUGET SOUND ENERGY INC
2,King,Bothell,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73.0,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,259.0,PACIFICORP
4,King,Seattle,2020,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)

In [12]:
# Irei trocar os títulos das celulas da coluna Clean alternative fuel para serem mais curtos e intuitivos
# Também trocar o nome da coluna para algo mais curto

df.rename(columns={"Clean Alternative Fuel Vehicle (CAFV) Eligibility": "CAFV Status"}, inplace=True)

mapeamento_CAFV = {
    "Clean Alternative Fuel Vehicle Eligible": "Eligible",
    "Not eligible due to low battery range": "Not Eligible (Low Range)",
    "Eligibility unknown as battery range has not been researched": np.nan
}

df["CAFV Status"] = df["CAFV Status"].map(mapeamento_CAFV)

df

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligible,215.0,PUGET SOUND ENERGY INC
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligible,73.0,PUGET SOUND ENERGY INC
2,King,Bothell,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Eligible,73.0,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Eligible,259.0,PACIFICORP
4,King,Seattle,2020,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not Eligible (Low Range),26.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
...,...,...,...,...,...,...,...,...,...
271108,Snohomish,Woodinville,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),NaN,NaN,PUGET SOUND ENERGY INC
271109,Skagit,Burlington,2024,RIVIAN,EDV,Battery Electric Vehicle (BEV),NaN,NaN,PUGET SOUND ENERGY INC
271110,Clark,Vancouver,2024,HONDA,PROLOGUE,Battery Electric Vehicle (BEV),NaN,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...
271111,Pierce,Tacoma,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not Eligible (Low Range),21.0,BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...
271112,King,Seattle,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not Eligible (Low Range),21.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)

In [13]:
# Também achei conveniente diminuir o tamanho das siglas na coluna de tipo de veículo

mapeamento_tipo = {"Battery Electric Vehicle (BEV)": "BEV",
"Plug-in Hybrid Electric Vehicle (PHEV)": "PHEV"}

df["Electric Vehicle Type"] = df["Electric Vehicle Type"].map(mapeamento_tipo)
df

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,PUGET SOUND ENERGY INC
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,PUGET SOUND ENERGY INC
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,PACIFICORP
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
...,...,...,...,...,...,...,...,...,...
271108,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,PUGET SOUND ENERGY INC
271109,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,PUGET SOUND ENERGY INC
271110,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...
271111,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...
271112,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)

In [14]:
# Verificando se as alterações foram bem sucedidas

df.columns

Index(['County', 'City', 'Model Year', 'Make', 'Model',
       'Electric Vehicle Type', 'CAFV Status', 'Electric Range',
       'Electric Utility'],
      dtype='object')

In [15]:
# Adicionando uma coluna com a idade do veículo em anos

df["Vehicle Age"] = (2026 - df["Model Year"])
df

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,PUGET SOUND ENERGY INC,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,PUGET SOUND ENERGY INC,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),15
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,PACIFICORP,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),6
...,...,...,...,...,...,...,...,...,...,...
271108,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,PUGET SOUND ENERGY INC,3
271109,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,PUGET SOUND ENERGY INC,2
271110,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,2
271111,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,3
271112,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),3

In [16]:
# Verificando os nomes dos itens da coluna de fornecedores

df["Electric Utility"].unique()

array(['PUGET SOUND ENERGY INC',
       'PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)', 'PACIFICORP',
       'CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)', 'AVISTA CORP',
       'PUD NO 1 OF CHELAN COUNTY', 'PUD NO 2 OF GRANT COUNTY',
       'MODERN ELECTRIC WATER COMPANY', 'PUD NO 1 OF DOUGLAS COUNTY',
       'NO KNOWN ELECTRIC UTILITY SERVICE',
       'PUD NO 1 OF PEND OREILLE COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF COWLITZ COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PUGET SOUND ENERGY INC||PUD NO 1 OF JEFFERSON COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||BENTON RURAL ELECTRIC ASSN',
       'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||PUD NO 1 OF CLARK COUNTY - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOHOMISH COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF PORT ANGELES - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLALLAM COUNTY',
       'CITY OF TACOMA - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KLICKITAT COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF MASON COUNTY|PUD NO 1 OF JEFFERSON COUNTY',
       'PORTLAND GENERAL ELECTRIC CO',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF MILTON - (WA)|CITY OF TACOMA - (WA)',
       'CITY OF CHEWELAH',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
       'CITY OF TACOMA - (WA)||TANNER ELECTRIC COOP',
       'CITY OF SEATTLE - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||INLAND POWER & LIGHT COMPANY',
       'PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||INLAND POWER & LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF WAHKIAKUM COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BENTON COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF RICHLAND - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FRANKLIN COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PARKLAND LIGHT & WATER COMPANY|PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF MASON COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 3 OF MASON COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||ORCAS POWER & LIGHT COOP',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF CENTRALIA - (WA)|CITY OF TACOMA - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||LAKEVIEW LIGHT & POWER|PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF LEWIS COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF GRAYS HARBOR COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ELMHURST MUTUAL POWER & LIGHT CO|PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||VERA IRRIGATION DISTRICT #15',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF PACIFIC COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF SKAMANIA CO',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KITTITAS COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF ELLENSBURG - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||TOWN OF STEILACOOM|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||BENTON RURAL ELECTRIC ASSN|PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||PUD NO 1 OF ASOTIN COUNTY',
       'CITY OF BLAINE - (WA)||PUD NO 1 OF WHATCOM COUNTY',
       'CITY OF CHENEY - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||BIG BEND ELECTRIC COOP, INC',
       'PUD NO 1 OF OKANOGAN COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||TOWN OF EATONVILLE - (WA)|CITY OF TACOMA - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||BIG BEND ELECTRIC COOP, INC',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||OHOP MUTUAL LIGHT COMPANY, INC|PENINSULA LIGHT COMPANY',
       'OKANOGAN COUNTY ELEC COOP, INC',
       'BONNEVILLE POWER ADMINISTRATION||BENTON RURAL ELECTRIC ASSN',
       'PUD NO 1 OF WHATCOM COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||TOWN OF RUSTON - (WA)|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF COULEE DAM - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||COLUMBIA RURAL ELEC ASSN, INC',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FERRY COUNTY',
       'CITY OF SUMAS - (WA)||PUD NO 1 OF WHATCOM COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ALDER MUTUAL LIGHT CO, INC|PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||COLUMBIA RURAL ELEC ASSN, INC',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF MCCLEARY - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||PENINSULA LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||NESPELEM VALLEY ELEC COOP, INC',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY||INLAND POWER & LIGHT COMPANY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF JEFFERSON COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY',
       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLALLAM COUNTY|PUD NO 1 OF JEFFERSON COUNTY'],
      dtype=object)

## Deixando as células da coluna de fornecedor de energia mais intuitivas

 Decidi remover certas nominações e símbolos presentes nas células, para deixa-las mais curtas e intuitivas. Olhando para o caso de *Bonneville* vemos um caso interessante, pois como citado acima é uma companhia estatal, logo os *PUDs*(*Public Utility District*), que são postos estatais que recebem energia da *Bonneville*.

In [17]:
# Limpando os nomes dos fornecedores de energia, removendo coisas com inc, WA, símbolos e nomes desnecessáriamente longos


#Retirando WA
df["Electric Utility"] = df["Electric Utility"].str.replace(" - (WA)", "", regex=False)

# Retirando - INC
df["Electric Utility"] = df["Electric Utility"].str.replace(" - INC", "", regex=False)

# Retirando INC
df["Electric Utility"] = df["Electric Utility"].str.replace("INC", "", regex=False)

# Retirando barras
df["Electric Utility"] = df["Electric Utility"].str.split("|").str[0]

# padronizando as células
df["Electric Utility"] = df["Electric Utility"].str.strip().str.title()

df["Electric Utility"] = df["Electric Utility"].str.strip()

mapeamento_fornecedores = {"NO KNOWN ELECTRIC UTILITY SERVICE": "Unknown","OKANOGAN COUNTY ELEC COOP,": 
                            "OKANOGAN COUNTY ELEC COOP",
                            "BONNEVILLE POWER ADMINISTRATION": "BPA (Local)"}

df["Electric Utility"] = df["Electric Utility"].replace(mapeamento_fornecedores)

df["Electric Utility"].unique()

array(['Puget Sound Energy', 'Pacificorp', 'City Of Seattle',
       'Avista Corp', 'Pud No 1 Of Chelan County',
       'Pud No 2 Of Grant County', 'Modern Electric Water Company',
       'Pud No 1 Of Douglas County', 'No Known Electric Utility Service',
       'Pud No 1 Of Pend Oreille County',
       'Bonneville Power Administration', 'City Of Tacoma',
       'Portland General Electric Co', 'City Of Chewelah',
       'City Of Blaine', 'City Of Cheney', 'Pud No 1 Of Okanogan County',
       'Okanogan County Elec Coop,', 'Pud No 1 Of Whatcom County',
       'City Of Sumas'], dtype=object)

In [18]:
# Casting da idade dos veículos para INT, pois anos são medidas inteiras

df["Vehicle Age"] = df["Vehicle Age"].astype(np.int64)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 270454 entries, 0 to 271112
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   County                 270454 non-null  object
 1   City                   270454 non-null  object
 2   Model Year             270454 non-null  int64
 3   Make                   270454 non-null  object
 4   Model                  270454 non-null  object
 5   Electric Vehicle Type  270454 non-null  object
 6   CAFV Status            100024 non-null  object
 7   Electric Range         100017 non-null  float64
 8   Electric Utility       270454 non-null  object
 9   Vehicle Age            270454 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 22.7+ MB

## Verificando outliers

 Para verificar a existência de *outliers* eu decidi identificar por meio do método de quartis, que se trata de encontrar os valores mais baixos(25% mais baixos) e mais altos(75% mais altos) e compará-los em relação a média das informações.

In [19]:
# Função para identificar outliers pelo método de quartis

def outliers_quartile(dataframe, coluna):
    """Função para identificar outliers com o método de boxplot/quartiles
    Troubleshooting: 1- Pandas não foi importado
    2- A variável coluna não foi escrito como string"""

    Q1 = dataframe[coluna].quantile(.25)
    Q3 = dataframe[coluna].quantile(.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    outliers = dataframe[(dataframe[coluna] < limite_inferior) | 
                         (dataframe[coluna] > limite_superior)]
    
    return outliers

## *Outliers* mas nem tanto...

 Como dito anteriormente, ao pesquisar por *outliers* na coluna de idade do veículo, se encontra valores como o do Ford Ranger, que foi lançado em 1999, porém não removi ele e outras *outliers*, visto que não é algo mentiroso, apenas algo comum em um *dataset* que abrange tantos anos.

In [20]:
# Verificando outliers nas colunas de idade, autonomia e ano de fabricação


outliers_quartile(df, "Vehicle Age")

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
12,Thurston,Olympia,2013,NISSAN,LEAF,BEV,Eligible,75.0,Puget Sound Energy,13
14,Yakima,Yakima,2016,TESLA,MODEL X,BEV,Eligible,200.0,Pacificorp,10
...,...,...,...,...,...,...,...,...,...,...
271017,Clallam,Port Angeles,2013,TESLA,MODEL S,BEV,Eligible,208.0,Bonneville Power Administration,13
271056,Snohomish,Arlington,2015,NISSAN,LEAF,BEV,Eligible,84.0,Bonneville Power Administration,11
271059,Snohomish,Snohomish,2015,FIAT,500,BEV,Eligible,87.0,Puget Sound Energy,11
271071,Whatcom,Bellingham,2015,TESLA,MODEL S,BEV,Eligible,208.0,Puget Sound Energy,11
271081,Skagit,Mount Vernon,2014,TESLA,MODEL S,BEV,Eligible,208.0,Puget Sound Energy,12

In [21]:
# Devido a muitos valores NaNs, foi retornado um Dataframe vazio
# Por segurança irei verificar de outra forma abaixo

outliers_quartile(df, "Electric Range")

Empty DataFrame
Columns: [County, City, Model Year, Make, Model, Electric Vehicle Type, CAFV Status, Electric Range, Electric Utility, Vehicle Age]
Index: []

In [22]:
# Após uma análise mais manual, nada de incomum foi encontrado

print(df["Electric Range"].quantile(.25))
print(df["Electric Range"].quantile(.75))
print(df["Electric Range"].max())

30.0
215.0
337.0

In [23]:
# Verificando os BEVs de forma separada

bevs = df[df["Electric Vehicle Type"] ==  "BEV"]

print(bevs["Electric Range"].quantile(.25))
print(bevs["Electric Range"].quantile(.75))
print(bevs["Electric Range"].max())

150.0
238.0
337.0

In [24]:
# Sem outliers em BEVs!

outliers_quartile(bevs, "Electric Range")

Empty DataFrame
Columns: [County, City, Model Year, Make, Model, Electric Vehicle Type, CAFV Status, Electric Range, Electric Utility, Vehicle Age]
Index: []

In [25]:
# Checando os PHEVs de forma avulsa agora

phevs = df[df["Electric Vehicle Type"] == "PHEV"]

print(phevs["Electric Range"].quantile(.25))
print(phevs["Electric Range"].quantile(.75))
print(phevs["Electric Range"].max())

21.0
38.0
153.0

## Mais falsas *outliers*

 Esses dados de são tão reais quanto o Ford Ranger, eles foram taxados como *outliers* pois a diferença tecnológica entre certos carros é enorme, Mas não existem dados mentiroso como um carro com 50.000 km de autonomia.

In [26]:
# Sem outliers em PHEVs também!

outliers_quartile(phevs,"Electric Range")

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
30,Thurston,Olympia,2018,BMW,I3,PHEV,Eligible,97.0,Puget Sound Energy,8
94,King,Renton,2014,BMW,I3,PHEV,Eligible,72.0,Puget Sound Energy,12
206,King,Seattle,2019,BMW,I3,PHEV,Eligible,126.0,City Of Seattle,7
220,Snohomish,Edmonds,2017,BMW,I3,PHEV,Eligible,97.0,Puget Sound Energy,9
295,Kitsap,Port Orchard,2017,BMW,I3,PHEV,Eligible,97.0,Puget Sound Energy,9
...,...,...,...,...,...,...,...,...,...,...
268849,Thurston,Olympia,2020,BMW,I3,PHEV,Eligible,126.0,Puget Sound Energy,6
269887,Island,Coupeville,2014,BMW,I3,PHEV,Eligible,72.0,Puget Sound Energy,12
270523,Whatcom,Bellingham,2019,BMW,I3,PHEV,Eligible,126.0,Puget Sound Energy,7
271075,King,Woodinville,2019,BMW,I3,PHEV,Eligible,126.0,Puget Sound Energy,7
271101,Klickitat,Trout Lake,2017,BMW,I3,PHEV,Eligible,97.0,Bonneville Power Administration,9

In [27]:
# última coluna ano de fabricação
# nada anormal, visto que é uma informação "casada" com a de idade do carro 

outliers_quartile(df,"Model Year")

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
12,Thurston,Olympia,2013,NISSAN,LEAF,BEV,Eligible,75.0,Puget Sound Energy,13
14,Yakima,Yakima,2016,TESLA,MODEL X,BEV,Eligible,200.0,Pacificorp,10
...,...,...,...,...,...,...,...,...,...,...
271017,Clallam,Port Angeles,2013,TESLA,MODEL S,BEV,Eligible,208.0,Bonneville Power Administration,13
271056,Snohomish,Arlington,2015,NISSAN,LEAF,BEV,Eligible,84.0,Bonneville Power Administration,11
271059,Snohomish,Snohomish,2015,FIAT,500,BEV,Eligible,87.0,Puget Sound Energy,11
271071,Whatcom,Bellingham,2015,TESLA,MODEL S,BEV,Eligible,208.0,Puget Sound Energy,11
271081,Skagit,Mount Vernon,2014,TESLA,MODEL S,BEV,Eligible,208.0,Puget Sound Energy,12

## Parte IV - Teste de sanidade e salvando o arquivo limpo
 A culminância da limpeza, talvez a parte mais simples desse *notebook*, mas a mais recompensadora; aqui foram executados testes de lógica e ajustes finais antes da exportação do arquivo para o formato CSV.

In [28]:
# Teste de lógica

df.describe()

          Model Year  Electric Range    Vehicle Age
count  270454.000000   100017.000000  270454.000000
mean     2021.995929      107.840707       4.004071
std         3.057503       97.173657       3.057503
min      1999.000000        1.000000       0.000000
25%      2021.000000       30.000000       2.000000
50%      2023.000000       48.000000       3.000000
75%      2024.000000      215.000000       5.000000
max      2026.000000      337.000000      27.000000

In [29]:
# Por segurança, irei resetar o index novamente

df.reset_index(drop=True)

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
...,...,...,...,...,...,...,...,...,...,...
270449,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,Puget Sound Energy,3
270450,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,Puget Sound Energy,2
270451,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,Bonneville Power Administration,2
270452,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,Bonneville Power Administration,3
270453,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,City Of Seattle,3

In [30]:
# Mais um último teste

df

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
...,...,...,...,...,...,...,...,...,...,...
271108,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,Puget Sound Energy,3
271109,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,Puget Sound Energy,2
271110,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,Bonneville Power Administration,2
271111,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,Bonneville Power Administration,3
271112,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,City Of Seattle,3

In [31]:
# Exportando o data frame limpo

df.to_csv(r"C:\Users\piaze\Documents\Projetos\EDA-Carros-Eletricos-Washington\base_de_dados\ev_dados_washington_limpo.csv", 
        index=False)

# Fim da limpeza!