# Análises, Plotagens e *Insights*
 Esse *notebook* contém gráficos e *insights* obtidos a partir do *Dataframe* que foi limpo no *notebook* anterior.

## Parte I - Carregamento dos Dados e Importações
 
 Muito similar a sessão de mesmo nome no *notebook* anterior, porém desta vez estou apenas checando se tudo feito lá funcionou, visto que já sei sobre os dados. Para evitar eventuais conflitos com o arquivo anterior chamarei o *dataframe* de **df_limpo**.

In [1]:
# Importação das bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
# Abrindo o arquivo e transformando em um dataframe

df_limpo = pd.read_csv(r"C:\Users\piaze\Documents\Projetos\EDA-Carros-Eletricos-Washington\base_de_dados\ev_dados_washington_limpo.csv")
df_limpo.head(10)

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
5,Thurston,Olympia,2023,KIA,NIRO,PHEV,Eligible,33.0,Puget Sound Energy,3
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
7,Thurston,Tumwater,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
8,Kitsap,Bremerton,2018,TESLA,MODEL S,BEV,Eligible,249.0,Puget Sound Energy,8
9,Snohomish,Lynnwood,2017,CHEVROLET,VOLT,PHEV,Eligible,53.0,Puget Sound Energy,9

## Parte II - Visão Geral da Frota

 Esta parte contém gráficos com informações gerais da frota, com base em todas as 270 mil linhas do *datafreame*, entre elas:

 **1 -** Top 10 marcas entre a frota, qual marca tem mais carros registrados?

 **2 -** BEV VS PHEV qual domina a frota?

 **3 -** Qual a proporção de idade na frota?

 **4 -** Qual a relação entre carros que são aptos ao *CAFV* e os que não?

 **5 -** E por fim, quais cidades tem a maior concentração de veículos?

In [3]:
# Separando as top 10 marcas

df_marcas = df_limpo["Make"].value_counts().reset_index()

df_marcas.columns = ["Marca", "Quantidade"]

top_10_marcas = df_marcas.head(10)


top_10_marcas

        Marca  Quantidade
0       TESLA      110210
1   CHEVROLET       19015
2      NISSAN       15938
3        FORD       14908
4         KIA       13600
5      TOYOTA       11350
6         BMW       11176
7     HYUNDAI        9806
8      RIVIAN        8491
9  VOLKSWAGEN        7356

In [4]:
# Top 10 marcas em gráfico

fig = px.bar(top_10_marcas, 
            x="Quantidade", 
            y="Marca", 
            title="<b>Figura 1: Top 10 Marcas na Frota<b>", 
            width=800, 
            height=600, 
            color="Marca", 
            color_discrete_sequence=px.colors.qualitative.D3)

fig.update_layout(title_x=0.5)

fig.show()

### Análise da figura 1
 
 Apesar de ser uma estatística muito simples, ela entrega muito sobre o panorama da frota, e até questionamentos sobre o mercado; Como: Apesar da sua recente tradição no mercado Norte-Americano porque a Tesla tem uma vantagem tão grande? A chinesa Rivian que "surgiu" recentemente no mercado americano parece ter um crescimento rápido e interessante.

In [5]:
# Divisão da frota, BEVs vs PHEVs

bev_vs_phev = df_limpo["Electric Vehicle Type"].value_counts().reset_index()
bev_vs_phev.columns = ["Tipo", "Quantidade"]

bev_vs_phev

   Tipo  Quantidade
0   BEV      215829
1  PHEV       54625

In [6]:
# Gráfico de pizza comparando os dois

fig = px.pie(bev_vs_phev, 
            values="Quantidade", 
            names="Tipo", 
            title="<b>Figura 2: Proporção entre BEVs e PHEVs na Frota<b>", 
            width=600,
            height=400,     
            color="Tipo",  
            color_discrete_map={"BEV": "#5B8DB8", "PHEV": "#B0B0B0"})

fig.update_layout(title_x=0.5, legend_title="Tipo")

fig.show()

### Análise da figura 2
 A imagem fala por si só, os BEVs dominam o mercado, e com uma rápida pesquisa em algum motor de busca ou até mesmo o site do governo de Washington, se percebe o porque: 1: O BEVs são mais acessíveis e tem isenções em certos impostos e 2: Por serem 100% elétricos sua mecânica é mais simples, sem um motor a combustão extra ou peças extras, o que gera um preço menor e maior facilidade na manutenção; Apesar de cada um ter suas vantagens específicas.

In [7]:
# Média de idade da frota

df_limpo["Vehicle Age"].mean().round()

np.float64(4.0)

In [8]:
# Agrupando por ano

evolucao_anual = df_limpo["Model Year"].value_counts().sort_index().reset_index()
evolucao_anual.columns = ["Ano", "Quantidade"]

fig = px.area(evolucao_anual, 
            x="Ano", 
            y="Quantidade",
            title="<b>Figura 3: Curva de Idade Entre a Frota<b>", 
            width=1000, 
            height=500)
             
fig.show()

## Análise da figura 3

 Com isso podemos chegar a duas possíveis conclusões, 1: as pessoas estão adotando EVs com um boom definitivo a partir de 2020 ou 2: As pessoas trocam de carro com frequência; logo não sabemos de seu veículo anterior já era elétrico. A verdade é um pouco dos dois, visto que o estado deu incentivos e iseções fiscais a carros elétricos um pouco antes do boom definitivo, o fato do poder de compra do país ser alto e cidades americanas tem navegação por outros meios se não o carro dificultada.

In [9]:
df_cafv = df_limpo.groupby(["Electric Vehicle Type", "CAFV Status"]).size().reset_index(name="Contagem")

df_cafv["CAFV Status"] = df_cafv["CAFV Status"].map({"Eligible": "Elegível","Not Eligible (Low Range)": "Não Elegível (Baixa Autonomia)"})

df_cafv

  Electric Vehicle Type                     CAFV Status  Contagem
0                   BEV                        Elegível     45391
1                   BEV  Não Elegível (Baixa Autonomia)         8
2                  PHEV                        Elegível     30632
3                  PHEV  Não Elegível (Baixa Autonomia)     23993

In [10]:
# Relação entre CAFV

fig = px.bar(df_cafv, 
             x="Electric Vehicle Type", 
             y="Contagem", 
             color="CAFV Status",
             title="<b>Figura 4: Correlação Entre Tipo Tecnológico e Elegibilidade CAFV</b>",
             barmode="stack",
             template="plotly_white")

fig.update_layout(xaxis_title="Tipo de Veículo", yaxis_title="Volume de Registros", legend_title="Status CAFV")

fig.show()

## Análise da figura 4

 É notável a diferença entre os dois tipos, mas isso tem uma explicação, o *CAFV* é uma medida que julga se o carro é *limpo* ou não, veículos com pelo menos **30 milhas** (48 Km aproximadamente) são considerados, isso vem da natureza dos veículos, obviamente se espera de um BEV uma autonomia muito superior usando apenas a bateria.

 Além disso o *CAFV* é um "bilhete" para a isenção de certos impostos.

In [11]:
# Cidades com mais carros

top_15_cidades = df_limpo["City"].value_counts().head(15).reset_index()
top_15_cidades.columns = ["Cidade", "Quantidade"]

top_15_cidades = top_15_cidades.sort_values(by="Quantidade", ascending=True, ignore_index=True)

top_15_cidades.head(15)

        Cidade  Quantidade
0      Everett        4266
1     Lynnwood        4425
2   Bellingham        4507
3      Spokane        4542
4         Kent        4622
5       Tacoma        5900
6      Olympia        6366
7       Renton        7448
8    Sammamish        7539
9     Kirkland        7702
10     Bothell        8936
11     Redmond        9242
12   Vancouver       10136
13    Bellevue       13120
14     Seattle       42105

In [12]:
# Plotando

fig = px.funnel(top_15_cidades,
            x="Quantidade", 
            y="Cidade",
            width=800, 
            height=600, 
            title="<b>Figura 5: Top 15 Cidades com Mais Veículos Registrados<b>",
            color="Cidade",
            color_discrete_sequence=px.colors.qualitative.Pastel)

fig.update_layout(title_x=0.5)

fig.show()

## Análise da figura 5

 Como esperado *Seattle* possui quase 4 vezes mais carros do que o segundo colocado; percebe-se também certa harmonia entre grupos, sendo que tirando *Seattle*, a subida das barras é bem suave e gradual.

 **Importante:** *Washington DC* não está em *Washington*, se trata de um estado a parte, similar ao distrito federal no Brasil.

## Parte III - Análise Entre Proporção na Frota e Autonomia

Dediquei esta parte para um panorama geral da evolução da tecnologia, decidi fazer vários *scatter plots*, agrupando os veículos por década, e analisando quantidade e autonomia. O *scatter plot* é perfeito, pois situações como muitas bolinhas juntas indicam uma média, algo com muita autonomia mais poucas unidades tende a ser um carro de luxo, que poucos podem comprar e um vice versa.

 Optei por fazer 2 gráficos sobre dois recortes históricos específicos, sendo 2015 - 2019 (O primeiro boom visto no gráfico da figura 3) e 2020 até 2026, o boom definitivo; assim também sendo possível comparar a evolução das tecnologias de autonomia

In [13]:
# Separando carros de 2015 até 2019

df_2015_2019 = df_limpo[(df_limpo["Model Year"] >= 2015) & (df_limpo["Model Year"] <= 2019)]

df_2015_2019

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
7,Thurston,Tumwater,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
8,Kitsap,Bremerton,2018,TESLA,MODEL S,BEV,Eligible,249.0,Puget Sound Energy,8
9,Snohomish,Lynnwood,2017,CHEVROLET,VOLT,PHEV,Eligible,53.0,Puget Sound Energy,9
...,...,...,...,...,...,...,...,...,...,...
270417,King,Woodinville,2019,BMW,I3,PHEV,Eligible,126.0,Puget Sound Energy,7
270434,Douglas,East Wenatchee,2019,SUBARU,CROSSTREK,PHEV,Not Eligible (Low Range),17.0,Pud No 1 Of Douglas County,7
270441,Pierce,Tacoma,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Bonneville Power Administration,8
270443,Klickitat,Trout Lake,2017,BMW,I3,PHEV,Eligible,97.0,Bonneville Power Administration,9
270445,King,Sammamish,2019,TESLA,MODEL 3,BEV,Eligible,220.0,Puget Sound Energy,7

In [14]:
# Criando uma tabela para os carros de 2015 à 2019, com modelo, autonomia e quantidade.

df_2015_2019_carros = df_2015_2019.groupby(["Make", "Model", "Electric Vehicle Type"]).agg({"Electric Range": "mean", "Model Year": "count"})

df_2015_2019_carros = df_2015_2019_carros.reset_index()

df_2015_2019_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,AUDI,A3,PHEV,16.000000,532
1,AUDI,E-TRON,BEV,204.000000,529
2,BMW,330E,PHEV,14.000000,179
3,BMW,530E,PHEV,14.944444,288
4,BMW,740E,PHEV,14.000000,26
5,BMW,I3,BEV,103.635659,387
6,BMW,I3,PHEV,90.447451,961
7,BMW,I8,PHEV,15.068966,87
8,BMW,X5,PHEV,13.621505,465
9,CADILLAC,CT6,PHEV,31.000000,13
10,CADILLAC,ELR,PHEV,38.857143,21
11,CHEVROLET,BOLT EV,BEV,238.000000,3551
12,CHEVROLET,SPARK,BEV,82.000000,168
13,CHEVROLET,VOLT,PHEV,51.069750,2681
14,CHRYSLER,PACIFICA,PHEV,32.841545,751
15,FIAT,500,BEV,85.101604,561
16,FORD,C-MAX,PHEV,19.317164,804
17,FORD,FOCUS,BEV,84.258065,93
18,FORD,FUSION,PHEV,20.547395,1171
19,HONDA,CLARITY,PHEV,47.000000,730
20,HYUNDAI,IONIQ,BEV,107.829787,48
21,HYUNDAI,IONIQ,PHEV,29.000000,72
22,HYUNDAI,KONA,BEV,258.000000,53
23,HYUNDAI,SONATA,PHEV,27.069444,72
24,JAGUAR,I-PACE,BEV,234.000000,36
25,KIA,NIRO,BEV,239.000000,405
26,KIA,NIRO,PHEV,26.000000,422
27,KIA,OPTIMA,PHEV,29.000000,89
28,KIA,SOUL,BEV,95.278481,556
29,MERCEDES-BENZ,B-CLASS,BEV,87.000000,54
30,MERCEDES-BENZ,C-CLASS,PHEV,8.750000,12
31,MERCEDES-BENZ,GLC-CLASS,PHEV,9.891026,156
32,MERCEDES-BENZ,GLE-CLASS,PHEV,8.930233,43
33,MERCEDES-BENZ,S-CLASS,PHEV,12.750000,8
34,MINI,COUNTRYMAN,PHEV,12.000000,156
35,MITSUBISHI,I-MIEV,BEV,61.727273,11
36,MITSUBISHI,OUTLANDER,PHEV,22.000000,327
37,NISSAN,LEAF,BEV,114.892729,5845
38,PORSCHE,918,PHEV,12.000000,2
39,PORSCHE,CAYENNE,PHEV,13.710084,238
40,PORSCHE,PANAMERA,PHEV,15.219780,91
41,SMART,EQ FORTWO,BEV,58.000000,54
42,SMART,FORTWO,BEV,62.350877,57
43,SMART,FORTWO ELECTRIC DRIVE,BEV,68.000000,41
44,SUBARU,CROSSTREK,PHEV,17.000000,93
45,TESLA,MODEL 3,BEV,217.004237,9677
46,TESLA,MODEL S,BEV,222.779523,3819
47,TESLA,MODEL X,BEV,227.763555,2453
48,TOYOTA,PRIUS,PHEV,6.000000,105
49,TOYOTA,PRIUS PRIME (PHEV),PHEV,25.000000,1806
50,VOLKSWAGEN,E-GOLF,BEV,107.122449,1029
51,VOLVO,S60,PHEV,22.000000,9
52,VOLVO,S90,PHEV,21.000000,23
53,VOLVO,XC60,PHEV,17.000000,228
54,VOLVO,XC90,PHEV,15.361111,360

In [15]:
# Juntando Marca, nome do modelo e tipo em uma célula só

df_2015_2019_carros["Model"] = df_2015_2019_carros["Make"] + " " + df_2015_2019_carros["Model"] + " " + df_2015_2019_carros["Electric Vehicle Type"]

df_2015_2019_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,AUDI,AUDI A3 PHEV,PHEV,16.000000,532
1,AUDI,AUDI E-TRON BEV,BEV,204.000000,529
2,BMW,BMW 330E PHEV,PHEV,14.000000,179
3,BMW,BMW 530E PHEV,PHEV,14.944444,288
4,BMW,BMW 740E PHEV,PHEV,14.000000,26
5,BMW,BMW I3 BEV,BEV,103.635659,387
6,BMW,BMW I3 PHEV,PHEV,90.447451,961
7,BMW,BMW I8 PHEV,PHEV,15.068966,87
8,BMW,BMW X5 PHEV,PHEV,13.621505,465
9,CADILLAC,CADILLAC CT6 PHEV,PHEV,31.000000,13
10,CADILLAC,CADILLAC ELR PHEV,PHEV,38.857143,21
11,CHEVROLET,CHEVROLET BOLT EV BEV,BEV,238.000000,3551
12,CHEVROLET,CHEVROLET SPARK BEV,BEV,82.000000,168
13,CHEVROLET,CHEVROLET VOLT PHEV,PHEV,51.069750,2681
14,CHRYSLER,CHRYSLER PACIFICA PHEV,PHEV,32.841545,751
15,FIAT,FIAT 500 BEV,BEV,85.101604,561
16,FORD,FORD C-MAX PHEV,PHEV,19.317164,804
17,FORD,FORD FOCUS BEV,BEV,84.258065,93
18,FORD,FORD FUSION PHEV,PHEV,20.547395,1171
19,HONDA,HONDA CLARITY PHEV,PHEV,47.000000,730
20,HYUNDAI,HYUNDAI IONIQ BEV,BEV,107.829787,48
21,HYUNDAI,HYUNDAI IONIQ PHEV,PHEV,29.000000,72
22,HYUNDAI,HYUNDAI KONA BEV,BEV,258.000000,53
23,HYUNDAI,HYUNDAI SONATA PHEV,PHEV,27.069444,72
24,JAGUAR,JAGUAR I-PACE BEV,BEV,234.000000,36
25,KIA,KIA NIRO BEV,BEV,239.000000,405
26,KIA,KIA NIRO PHEV,PHEV,26.000000,422
27,KIA,KIA OPTIMA PHEV,PHEV,29.000000,89
28,KIA,KIA SOUL BEV,BEV,95.278481,556
29,MERCEDES-BENZ,MERCEDES-BENZ B-CLASS BEV,BEV,87.000000,54
30,MERCEDES-BENZ,MERCEDES-BENZ C-CLASS PHEV,PHEV,8.750000,12
31,MERCEDES-BENZ,MERCEDES-BENZ GLC-CLASS PHEV,PHEV,9.891026,156
32,MERCEDES-BENZ,MERCEDES-BENZ GLE-CLASS PHEV,PHEV,8.930233,43
33,MERCEDES-BENZ,MERCEDES-BENZ S-CLASS PHEV,PHEV,12.750000,8
34,MINI,MINI COUNTRYMAN PHEV,PHEV,12.000000,156
35,MITSUBISHI,MITSUBISHI I-MIEV BEV,BEV,61.727273,11
36,MITSUBISHI,MITSUBISHI OUTLANDER PHEV,PHEV,22.000000,327
37,NISSAN,NISSAN LEAF BEV,BEV,114.892729,5845
38,PORSCHE,PORSCHE 918 PHEV,PHEV,12.000000,2
39,PORSCHE,PORSCHE CAYENNE PHEV,PHEV,13.710084,238
40,PORSCHE,PORSCHE PANAMERA PHEV,PHEV,15.219780,91
41,SMART,SMART EQ FORTWO BEV,BEV,58.000000,54
42,SMART,SMART FORTWO BEV,BEV,62.350877,57
43,SMART,SMART FORTWO ELECTRIC DRIVE BEV,BEV,68.000000,41
44,SUBARU,SUBARU CROSSTREK PHEV,PHEV,17.000000,93
45,TESLA,TESLA MODEL 3 BEV,BEV,217.004237,9677
46,TESLA,TESLA MODEL S BEV,BEV,222.779523,3819
47,TESLA,TESLA MODEL X BEV,BEV,227.763555,2453
48,TOYOTA,TOYOTA PRIUS PHEV,PHEV,6.000000,105
49,TOYOTA,TOYOTA PRIUS PRIME (PHEV) PHEV,PHEV,25.000000,1806
50,VOLKSWAGEN,VOLKSWAGEN E-GOLF BEV,BEV,107.122449,1029
51,VOLVO,VOLVO S60 PHEV,PHEV,22.000000,9
52,VOLVO,VOLVO S90 PHEV,PHEV,21.000000,23
53,VOLVO,VOLVO XC60 PHEV,PHEV,17.000000,228
54,VOLVO,VOLVO XC90 PHEV,PHEV,15.361111,360

In [16]:
# Removendo colunas desnecessárias, renomeando colunas e  arredondando a autonomia


df_2015_2019_carros = df_2015_2019_carros.rename(columns={"Model Year": "Quantidade", "Electric Range": "Autonomia", "Model": "Modelo"})

df_2015_2019_carros.drop(columns=["Make", "Electric Vehicle Type"], inplace=True)

df_2015_2019_carros["Autonomia"] = df_2015_2019_carros["Autonomia"].round()

df_2015_2019_carros

                             Modelo  Autonomia  Quantidade
0                      AUDI A3 PHEV       16.0         532
1                   AUDI E-TRON BEV      204.0         529
2                     BMW 330E PHEV       14.0         179
3                     BMW 530E PHEV       15.0         288
4                     BMW 740E PHEV       14.0          26
5                        BMW I3 BEV      104.0         387
6                       BMW I3 PHEV       90.0         961
7                       BMW I8 PHEV       15.0          87
8                       BMW X5 PHEV       14.0         465
9                 CADILLAC CT6 PHEV       31.0          13
10                CADILLAC ELR PHEV       39.0          21
11            CHEVROLET BOLT EV BEV      238.0        3551
12              CHEVROLET SPARK BEV       82.0         168
13              CHEVROLET VOLT PHEV       51.0        2681
14           CHRYSLER PACIFICA PHEV       33.0         751
15                     FIAT 500 BEV       85.0         561
16                  FORD C-MAX PHEV       19.0         804
17                   FORD FOCUS BEV       84.0          93
18                 FORD FUSION PHEV       21.0        1171
19               HONDA CLARITY PHEV       47.0         730
20                HYUNDAI IONIQ BEV      108.0          48
21               HYUNDAI IONIQ PHEV       29.0          72
22                 HYUNDAI KONA BEV      258.0          53
23              HYUNDAI SONATA PHEV       27.0          72
24                JAGUAR I-PACE BEV      234.0          36
25                     KIA NIRO BEV      239.0         405
26                    KIA NIRO PHEV       26.0         422
27                  KIA OPTIMA PHEV       29.0          89
28                     KIA SOUL BEV       95.0         556
29        MERCEDES-BENZ B-CLASS BEV       87.0          54
30       MERCEDES-BENZ C-CLASS PHEV        9.0          12
31     MERCEDES-BENZ GLC-CLASS PHEV       10.0         156
32     MERCEDES-BENZ GLE-CLASS PHEV        9.0          43
33       MERCEDES-BENZ S-CLASS PHEV       13.0           8
34             MINI COUNTRYMAN PHEV       12.0         156
35            MITSUBISHI I-MIEV BEV       62.0          11
36        MITSUBISHI OUTLANDER PHEV       22.0         327
37                  NISSAN LEAF BEV      115.0        5845
38                 PORSCHE 918 PHEV       12.0           2
39             PORSCHE CAYENNE PHEV       14.0         238
40            PORSCHE PANAMERA PHEV       15.0          91
41              SMART EQ FORTWO BEV       58.0          54
42                 SMART FORTWO BEV       62.0          57
43  SMART FORTWO ELECTRIC DRIVE BEV       68.0          41
44            SUBARU CROSSTREK PHEV       17.0          93
45                TESLA MODEL 3 BEV      217.0        9677
46                TESLA MODEL S BEV      223.0        3819
47                TESLA MODEL X BEV      228.0        2453
48                TOYOTA PRIUS PHEV        6.0         105
49   TOYOTA PRIUS PRIME (PHEV) PHEV       25.0        1806
50            VOLKSWAGEN E-GOLF BEV      107.0        1029
51                   VOLVO S60 PHEV       22.0           9
52                   VOLVO S90 PHEV       21.0          23
53                  VOLVO XC60 PHEV       17.0         228
54                  VOLVO XC90 PHEV       15.0         360

In [17]:
# Plotando...

fig = px.scatter(df_2015_2019_carros,
                y="Autonomia",
                x="Quantidade",
                size="Quantidade",
                title="<b>Figura 6: Relação de Autonomia e Quantidade Registrada 2015 - 2019<b>",
                color="Modelo",
                labels={"Autonomia": "Autonomia em Milhas"},
                color_discrete_sequence=px.colors.qualitative.Bold,
                template="plotly_white")


fig.show()

### Análise da Figura 6

 Vemos um mercado bem diverso, com inúmeros PHEVs no canto inferior esquerdo, e modelos BEV da Tesla, Chevrolet, Hyundai e Nissan perto do topo da autonomia, mas novamente a Tesla domina, emplacando muitos modelos em no topo do centro e no topo da direita. Támbem se percebe pequenas bolinhas no canto superior esquerdo, que são BEVs de marcas de luxo como a Jaguar e Audi.

In [18]:
# Começando tudo denovo para 2020 - 2026

df_2020_2026 = df_limpo[(df_limpo["Model Year"] >= 2020) & (df_limpo["Model Year"] <= 2026)]

df_2020_2026.reset_index()

df_2020_2026

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
5,Thurston,Olympia,2023,KIA,NIRO,PHEV,Eligible,33.0,Puget Sound Energy,3
10,Snohomish,Bothell,2024,BMW,X5,PHEV,Eligible,39.0,Puget Sound Energy,2
17,Kitsap,Silverdale,2020,TESLA,MODEL Y,BEV,Eligible,291.0,Puget Sound Energy,6
...,...,...,...,...,...,...,...,...,...,...
270449,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,Puget Sound Energy,3
270450,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,Puget Sound Energy,2
270451,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,Bonneville Power Administration,2
270452,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,Bonneville Power Administration,3
270453,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,City Of Seattle,3

In [19]:
# Repetindo a unificação

df_2020_2026_carros = df_2020_2026.groupby(["Make", "Model", "Electric Vehicle Type"]).agg({"Electric Range": "mean", "Model Year": "count"})

df_2020_2026_carros = df_2020_2026_carros.reset_index()

df_2020_2026_carros

           Make   Model Electric Vehicle Type  Electric Range  Model Year
0         ACURA     ZDX                   BEV             NaN         355
1    ALFA ROMEO  TONALE                  PHEV       33.000000          98
2          AUDI      A6                   BEV             NaN          51
3          AUDI    A7 E                  PHEV       24.000000          11
4          AUDI    A8 E                  PHEV       17.000000           4
..          ...     ...                   ...             ...         ...
154       VOLVO     S90                  PHEV       35.000000          17
155       VOLVO     V60                  PHEV       39.100000         100
156       VOLVO    XC40                   BEV             NaN        1388
157       VOLVO    XC60                  PHEV       30.424608        1658
158       VOLVO    XC90                  PHEV       27.677062        1988

[159 rows x 5 columns]

In [20]:
# Jutando informações novamente

df_2020_2026_carros["Model"] = df_2020_2026_carros["Make"] + " " + df_2020_2026_carros["Model"] + " " + df_2020_2026_carros["Electric Vehicle Type"]

df_2020_2026_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,ACURA,ACURA ZDX BEV,BEV,NaN,355
1,ALFA ROMEO,ALFA ROMEO TONALE PHEV,PHEV,33.000000,98
2,AUDI,AUDI A6 BEV,BEV,NaN,51
3,AUDI,AUDI A7 E PHEV,PHEV,24.000000,11
4,AUDI,AUDI A8 E PHEV,PHEV,17.000000,4
...,...,...,...,...,...
154,VOLVO,VOLVO S90 PHEV,PHEV,35.000000,17
155,VOLVO,VOLVO V60 PHEV,PHEV,39.100000,100
156,VOLVO,VOLVO XC40 BEV,BEV,NaN,1388
157,VOLVO,VOLVO XC60 PHEV,PHEV,30.424608,1658
158,VOLVO,VOLVO XC90 PHEV,PHEV,27.677062,1988

### Surgem NaNs!

Como citado antes, alguns carros não tem sua autonomia registrada e constam como valores NaNs, como em um gráfico eles são ignorados, decidi por remover eles.

In [21]:
# Removendo NaNs

df_2020_2026_carros = df_2020_2026_carros.dropna(subset=["Electric Range"])

df_2020_2026_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
1,ALFA ROMEO,ALFA ROMEO TONALE PHEV,PHEV,33.000000,98
3,AUDI,AUDI A7 E PHEV,PHEV,24.000000,11
4,AUDI,AUDI A8 E PHEV,PHEV,17.000000,4
5,AUDI,AUDI E-TRON BEV,BEV,222.000000,678
7,AUDI,AUDI E-TRON SPORTBACK BEV,BEV,218.000000,208
...,...,...,...,...,...
153,VOLVO,VOLVO S60 PHEV,PHEV,32.857143,196
154,VOLVO,VOLVO S90 PHEV,PHEV,35.000000,17
155,VOLVO,VOLVO V60 PHEV,PHEV,39.100000,100
157,VOLVO,VOLVO XC60 PHEV,PHEV,30.424608,1658
158,VOLVO,VOLVO XC90 PHEV,PHEV,27.677062,1988

In [22]:
# Removendo as colunas inúteis e arredondando a autonomia

df_2020_2026_carros = df_2020_2026_carros.drop(columns=["Make", "Electric Vehicle Type"])

df_2020_2026_carros["Electric Range"] = df_2020_2026_carros["Electric Range"].round()

df_2020_2026_carros.reset_index()

df_2020_2026_carros

                         Model  Electric Range  Model Year
1       ALFA ROMEO TONALE PHEV            33.0          98
3               AUDI A7 E PHEV            24.0          11
4               AUDI A8 E PHEV            17.0           4
5              AUDI E-TRON BEV           222.0         678
7    AUDI E-TRON SPORTBACK BEV           218.0         208
..                         ...             ...         ...
153             VOLVO S60 PHEV            33.0         196
154             VOLVO S90 PHEV            35.0          17
155             VOLVO V60 PHEV            39.0         100
157            VOLVO XC60 PHEV            30.0        1658
158            VOLVO XC90 PHEV            28.0        1988

[79 rows x 3 columns]

In [23]:
# Renomeando as colunas

df_2020_2026_carros = df_2020_2026_carros.rename(columns={"Model": "Modelo", "Electric Range": "Autonomia", "Model Year": "Quantidade"})

df_2020_2026_carros

                        Modelo  Autonomia  Quantidade
1       ALFA ROMEO TONALE PHEV       33.0          98
3               AUDI A7 E PHEV       24.0          11
4               AUDI A8 E PHEV       17.0           4
5              AUDI E-TRON BEV      222.0         678
7    AUDI E-TRON SPORTBACK BEV      218.0         208
..                         ...        ...         ...
153             VOLVO S60 PHEV       33.0         196
154             VOLVO S90 PHEV       35.0          17
155             VOLVO V60 PHEV       39.0         100
157            VOLVO XC60 PHEV       30.0        1658
158            VOLVO XC90 PHEV       28.0        1988

[79 rows x 3 columns]

In [24]:
# Plotando

fig = px.scatter(df_2020_2026_carros,
                x="Quantidade",
                y="Autonomia",
                size="Quantidade",
                title="<b>Figura 7: Relação de Autonomia e Quantidade Registrada 2020- 2026<b>",
                color="Modelo",
                labels={"Autonomia": "Autonomia em Milhas"},
                color_discrete_sequence=px.colors.qualitative.Alphabet,
                template="plotly_white")

fig.show()

### Análise figura 7

 Pode se observar que, os Teslas são os reis da autonomia e tem dezenhas de milhares de unidades circulando, vemos que a média principalmente dos PHEV é na casa dos 30 até 50 km de autonomia, visto o alto número de bolinhas juntas no canto inferirior esquerdo.

  Támbem se observa que apenas modelos de luxo como Polestar e Porsche fazem frente a autonomia da Tesla, mas sua bolinha pequena e próxima a esquerda aponta que são poucas unidades em circulação.

## Parte IV - Consolidando a Percepção de Monopólio

 Nos gráficos da figura 1 e posteriormente nos 6 e 7, percebi que a Tesla domina amplamente a frota em questões de números, seja em um recorte específico como nos gráficos 6 e 7 ou em um recorte geral como no 1; Mas em números o quão grande é o fatia dela no *marketshare*?, por isso decidi dedicar esta última parte de plotagem para conceber isso em porcentagem.

In [25]:
# Separando o marketshare

marketshare = df_limpo["Make"].value_counts(normalize=True).reset_index()

marketshare.columns = ["Marca", "Participação"]

marketshare["Participação"] = (marketshare["Participação"] * 100).round(1)

marketshare

                     Marca  Participação
0                    TESLA          40.7
1                CHEVROLET           7.0
2                   NISSAN           5.9
3                     FORD           5.5
4                      KIA           5.0
5                   TOYOTA           4.2
6                      BMW           4.1
7                  HYUNDAI           3.6
8                   RIVIAN           3.1
9               VOLKSWAGEN           2.7
10                   VOLVO           2.6
11                    JEEP           2.5
12                    AUDI           2.1
13                CHRYSLER           1.4
14           MERCEDES-BENZ           1.2
15                   HONDA           1.1
16                  SUBARU           1.0
17                CADILLAC           0.8
18                 PORSCHE           0.7
19                POLESTAR           0.6
20                   MAZDA           0.6
21                   LEXUS           0.5
22              MITSUBISHI           0.5
23                    MINI           0.4
24                    FIAT           0.3
25                   DODGE           0.3
26                   LUCID           0.2
27                     GMC           0.2
28                 GENESIS           0.2
29                 LINCOLN           0.2
30                   ACURA           0.1
31                   SMART           0.1
32              LAND ROVER           0.1
33                  JAGUAR           0.1
34                  FISKER           0.1
35              ALFA ROMEO           0.0
36              BRIGHTDROP           0.0
37             LAMBORGHINI           0.0
38                     RAM           0.0
39                 BENTLEY           0.0
40             ROLLS-ROYCE           0.0
41                   TH!NK           0.0
42                 VINFAST           0.0
43          AZURE DYNAMICS           0.0
44    WHEEGO ELECTRIC CARS           0.0
45  MULLEN AUTOMOTIVE INC.           0.0
46                MASERATI           0.0

In [26]:
# Plotando as informações

fig = px.treemap(marketshare,
                path=["Marca"],
                values="Participação",
                color="Marca",
                color_discrete_sequence=px.colors.qualitative.Prism,
                title="<b> Figura 8: Marketshare Geral em Porcentagem",)

fig.update_traces(
    textinfo="label+value", 
    texttemplate="<b>%{label}</b><br>%{value:.1f}%",
    textfont_size=14,)

fig.update_layout(title_x=0.5)

fig.show()

### Análise figura 8

 Como já foi apontado em gráficos anteriores a Tesla domina o mercado, mesmo considerando todos o veículos da frota como no gráfico acima, outras marcas beiram os 7 até 4 porcento, brigando para serem o melhor do resto; e após isso entram participações minúsculas de marcas nichadas e de luxo.

## Veredito Final
 O estado de Washington apresenta um mercado de veículos elétricos maduro tecnologicamente, mas comercialmente praticamente monopólico. O desafio para os próximos anos não é mais a autonomia das baterias, mas sim a diversificação da oferta para quebrar a atual concentração de *marketshare* e democratizar o acesso através de novas fabricantes e modelos elegíveis aos incentivos governamentais (*CAFV*).