# Análises, plotagens e *insights*
 Esse *notebook* contém gráficos e *insights* obtidos a partir do *Dataframe* que foi limpo no *notebook* anterior.

## Parte I - Carregamento dos dados e importações
 
 Muito similar a sessão de mesma parte no *notebook* anterior, porém desta vez estou apenas checando se tudo feito lá funcionou, visto que já sei sobre os dados. Para evitar eventuais conflitos com o arquivo anterior chamarei o *dataframe* de **df_limpo**; O mesmo vale para outros que possam aparecer posteriormente, mas sempre irei explicar seu *alias*.

In [261]:
# Importação das bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [262]:
# Abrindo o arquivo e transformando em um dataframe

df_limpo = pd.read_csv(r"C:\Users\piaze\Documents\Projetos\EDA-Carros-Eletricos-Washington\base_de_dados\ev_dados_washington_limpo.csv")
df_limpo.head(10)

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
5,Thurston,Olympia,2023,KIA,NIRO,PHEV,Eligible,33.0,Puget Sound Energy,3
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
7,Thurston,Tumwater,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
8,Kitsap,Bremerton,2018,TESLA,MODEL S,BEV,Eligible,249.0,Puget Sound Energy,8
9,Snohomish,Lynnwood,2017,CHEVROLET,VOLT,PHEV,Eligible,53.0,Puget Sound Energy,9

## Parte II - Visão geral da frota

 Esta parte contém gráficos com informações gerais da frota, com base em todas as 270 mil linhas do *datafreame*, entre elas:

 **1 -** Top 10 marcas entre a frota, qual marca tem mais carros registrados?

 **2 -** BEV VS PHEV qual domina a frota?

 **3 -** Qual idade média da frota?

 **4 -** Qual a relação entre carros que são aptos ao *CAFV* e os que não?

 **5 -** E por fim, quais cidades tem a maior concentração de veículos?

In [263]:
# Separando as top 10 marcas

df_marcas = df_limpo["Make"].value_counts().reset_index()

df_marcas.columns = ["Marca", "Quantidade"]

top_10_marcas = df_marcas.head(10)


top_10_marcas

        Marca  Quantidade
0       TESLA      110210
1   CHEVROLET       19015
2      NISSAN       15938
3        FORD       14908
4         KIA       13600
5      TOYOTA       11350
6         BMW       11176
7     HYUNDAI        9806
8      RIVIAN        8491
9  VOLKSWAGEN        7356

In [264]:
# Top 10 marcas em gráfico

fig = px.bar(top_10_marcas, 
            x="Quantidade", 
            y="Marca", 
            title="<b>Figura 1: Top 10 marcas na frota<b>", 
            width=800, 
            height=600, 
            color="Marca", 
            color_discrete_sequence=px.colors.qualitative.D3)

fig.update_layout(title_x=0.5)

fig.show()

### Análise da figura 1
 
 Apesar de ser uma estatística muito simples, ela entrega muito sobre o panorama da frota, e até questionamentos sobre o mercado; Como: Apesar da sua recente tradição no mercado Norte-Americano porque a Tesla tem uma vantagem tão grande? A chinesa Rivian que "surgiu" recentemente no mercado americano parece ter um crescimento rápido e interessante.

In [265]:
# Divisão da frota, BEVs vs PHEVs

bev_vs_phev = df_limpo["Electric Vehicle Type"].value_counts().reset_index()
bev_vs_phev.columns = ["Tipo", "Quantidade"]

bev_vs_phev

   Tipo  Quantidade
0   BEV      215829
1  PHEV       54625

In [266]:
# Gráfico de pizza comparando os dois

fig = px.pie(bev_vs_phev, 
            values="Quantidade", 
            names="Tipo", 
            title="<b>Figura 2: Proporção entre BEVs e PHEVs na frota<b>", 
            width=600,
            height=400,     
            color='Tipo',  
            color_discrete_map={"BEV": "#5B8DB8", "PHEV": "#B0B0B0"})

fig.update_layout(title_x=0.5, legend_title="Tipo")

fig.show()

### Análise da figura 2
 A imagem fala por si só, os BEVs dominam o mercado, e com uma rápida pesquisa em algum motor de busca ou até mesmo o site do governo de Washington, se percebe o porque: 1: O BEVs são mais acessíveis e tem isenções em certos impostos e 2: Por serem 100% elétricos sua mecânica é mais simples, sem um motor a combustão extra ou peças extras, o que gera um preço menor e maior facilidade na manutenção; Apesar de cada um ter suas vantagens específicas.

In [267]:
# Média de idade da frota

df_limpo["Vehicle Age"].mean().round()

np.float64(4.0)

In [268]:
# Agrupando por ano

evolucao_anual = df_limpo["Model Year"].value_counts().sort_index().reset_index()
evolucao_anual.columns = ["Ano", "Quantidade"]

fig = px.area(evolucao_anual, 
            x="Ano", 
            y="Quantidade",
            title="<b>Figura 3: Curva de idade entre a frota<b>", 
            width=1000, 
            height=500)
             

fig.update_traces(line_color='#1f77b4')

fig.show()

## Análise da figura 3

 Com isso podemos chegar a duas possíveis conclusões, 1: as pessoas estão adotando EVs com um boom definitivo a partir de 2020 ou 2: As pessoas trocam de carro com frequência; logo não sabemos de seu veículo anterior já era elétrico. A verdade é um pouco dos dois, visto que o estado deu incentivos e iseções fiscais a carros elétricos um pouco antes do boom definitivo, o fato do poder de compra do país ser alto e cidades americanas tem navegação por outros meios se não o carro dificultada.

In [269]:
df_cafv = df_limpo.groupby(['Electric Vehicle Type', 'CAFV Status']).size().reset_index(name='Contagem')

df_cafv["CAFV Status"] = df_cafv["CAFV Status"].map({"Eligible": "Elegível","Not Eligible (Low Range)": "Não Elegível (Baixa Autonomia)"})

df_cafv

  Electric Vehicle Type                     CAFV Status  Contagem
0                   BEV                        Elegível     45391
1                   BEV  Não Elegível (Baixa Autonomia)         8
2                  PHEV                        Elegível     30632
3                  PHEV  Não Elegível (Baixa Autonomia)     23993

In [270]:
# Relação entre CAFV

fig = px.bar(df_cafv, 
             x="Electric Vehicle Type", 
             y="Contagem", 
             color="CAFV Status",
             title="<b>Figura 4: Correlação entre Tipologia Tecnológica e Elegibilidade CAFV</b>",
             barmode="stack",
             template="plotly_white")

fig.update_layout(xaxis_title="Tipo de Veículo", yaxis_title="Volume de Registros", legend_title="Status CAFV")

fig.show()

## Análise da figura 4

 É notável a diferença entre os dois tipos, mas isso tem uma explicação, o *CAFV* é uma medida que julga se o carro é *limpo* ou não, veículos com pelo menos **30 milhas** (48 Km aproximadamente) são considerados, isso vem da natureza dos veículos, obviamente se espera de um BEV uma autonomia muito superior usando apenas a bateria.

 Além disso o *CAFV* é um "bilhete" para a isenção de certos impostos.

In [271]:
# Cidades com mais carros

top_15_cidades = df_limpo["City"].value_counts().head(15).reset_index()
top_15_cidades.columns = ["Cidade", "Quantidade"]

top_15_cidades = top_15_cidades.sort_values(by="Quantidade", ascending=True, ignore_index=True)

top_15_cidades.head(15)

        Cidade  Quantidade
0      Everett        4266
1     Lynnwood        4425
2   Bellingham        4507
3      Spokane        4542
4         Kent        4622
5       Tacoma        5900
6      Olympia        6366
7       Renton        7448
8    Sammamish        7539
9     Kirkland        7702
10     Bothell        8936
11     Redmond        9242
12   Vancouver       10136
13    Bellevue       13120
14     Seattle       42105

In [272]:
# Plotando

fig = px.funnel(top_15_cidades,
            x='Quantidade', 
            y='Cidade',
            width=800, 
            height=600, 
            title="<b>Figura 5: Top 15 cidades com mais veículos registrados<b>",
            color="Cidade",
            color_discrete_sequence=px.colors.qualitative.Pastel)

fig.update_layout(title_x=0.5)

fig.show()

## Análise da figura 5

 Como esperado *Seattle* possui quase 4 vezes mais carros do que o segundo colocado; percebe-se também certa harmonia entre grupos, sendo que tirando *Seattle*, a subida das barras é bem suave e gradual.

 **Importante:** *Washington DC* não está em *Washington*, se trata de um estado a parte, similar ao distrito federal no Brasil.

## Parte III

Dediquei esta parte para um panorama geral da evolução da tecnologia, decidi fazer vários *scatter plots*, agrupando os veículos por década, e analisando quantidade e autonomia. O *scatter plot* é perfeito, pois situações como muitas bolinhas juntas indicam uma média, algo com muita autonomia mais poucas unidades tende a ser um carro de luxo, que poucos podem comprar e um vice versa.

In [273]:
# separando carros de 1999 - 2009

df_1999_2009 = df_limpo[(df_limpo["Model Year"] >= 1999) & (df_limpo["Model Year"] < 2009)]

df_1999_2009

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
6968,King,Kirkland,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
18491,Kitsap,Port Orchard,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
18814,King,Burien,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
31478,King,Shoreline,2000,FORD,RANGER,BEV,Eligible,58.0,City Of Seattle,26
39338,King,Redmond,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
43101,King,Shoreline,2000,FORD,RANGER,BEV,Eligible,58.0,City Of Seattle,26
57168,King,Seattle,2008,TESLA,ROADSTER,BEV,Eligible,220.0,City Of Seattle,18
67285,King,Seattle,2008,TESLA,ROADSTER,BEV,Eligible,220.0,City Of Seattle,18
67845,King,Issaquah,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
69155,King,Seattle,2000,FORD,RANGER,BEV,Eligible,58.0,City Of Seattle,26
93260,King,Seattle,2000,FORD,RANGER,BEV,Eligible,58.0,City Of Seattle,26
95788,King,Seattle,2008,TESLA,ROADSTER,BEV,Eligible,220.0,City Of Seattle,18
97206,Thurston,Olympia,2000,FORD,RANGER,BEV,Eligible,58.0,Puget Sound Energy,26
100439,Kitsap,Kingston,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
100905,King,Seattle,2008,TESLA,ROADSTER,BEV,Eligible,220.0,City Of Seattle,18
105303,King,Seattle,2008,TESLA,ROADSTER,BEV,Eligible,220.0,City Of Seattle,18
140280,San Juan,Friday Harbor,2008,TESLA,ROADSTER,BEV,NaN,NaN,Bonneville Power Administration,18
142981,Snohomish,Snohomish,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
152720,San Juan,Friday Harbor,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Bonneville Power Administration,18
162837,Clallam,Sequim,2002,TOYOTA,RAV4,BEV,Eligible,95.0,Bonneville Power Administration,24
165018,King,Bellevue,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
169230,Pierce,Graham,1999,FORD,RANGER,BEV,Eligible,74.0,Bonneville Power Administration,27
172910,Pierce,Graham,1999,FORD,RANGER,BEV,Eligible,74.0,Bonneville Power Administration,27
188514,King,Redmond,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
191884,Pierce,Lakewood,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Bonneville Power Administration,18
207266,Whatcom,Everson,2000,FORD,RANGER,BEV,Eligible,58.0,Puget Sound Energy,26
229549,Spokane,Spokane,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Bonneville Power Administration,18
229777,Pierce,Gig Harbor,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Bonneville Power Administration,18
238844,San Juan,Friday Harbor,2000,FORD,RANGER,BEV,Eligible,58.0,Bonneville Power Administration,26
240346,Whatcom,Everson,2000,FORD,RANGER,BEV,Eligible,58.0,Puget Sound Energy,26
244920,Whatcom,Ferndale,2008,TESLA,ROADSTER,BEV,Eligible,220.0,Puget Sound Energy,18
258376,San Juan,Friday Harbor,2003,TOYOTA,RAV4,BEV,Eligible,95.0,Bonneville Power Administration,23

In [274]:
# Criando um dataframe com os carros de 1999 até 2009, 
# com informações de modelo (Marca + Modelo, concatenados), autonomia e quantidades registradas

df_1999_2009_carros = df_1999_2009.groupby(["Make", "Model", "Electric Vehicle Type"]).agg({"Electric Range": "mean", "Model Year": "count"})

df_1999_2009_carros = df_1999_2009_carros.reset_index()

df_1999_2009_carros

     Make     Model Electric Vehicle Type  Electric Range  Model Year
0    FORD    RANGER                   BEV            61.2          10
1   TESLA  ROADSTER                   BEV           220.0          20
2  TOYOTA      RAV4                   BEV            95.0           2

In [275]:
# Unificando marca, modelo e tipo

df_1999_2009_carros["Model"] = df_1999_2009_carros["Make"] + " " + df_1999_2009_carros["Model"] + " " + df_1999_2009_carros["Electric Vehicle Type"]

df_1999_2009_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,FORD,FORD RANGER BEV,BEV,61.2,10
1,TESLA,TESLA ROADSTER BEV,BEV,220.0,20
2,TOYOTA,TOYOTA RAV4 BEV,BEV,95.0,2

In [276]:
# Tratando as colunas

df_1999_2009_carros = df_1999_2009_carros.rename(columns={"Model Year": "Quantidade", "Electric Range": "Autonomia", "Model": "Modelo"})

df_1999_2009_carros.drop(columns=["Make", "Electric Vehicle Type"], inplace=True)

df_1999_2009_carros

               Modelo  Autonomia  Quantidade
0     FORD RANGER BEV       61.2          10
1  TESLA ROADSTER BEV      220.0          20
2     TOYOTA RAV4 BEV       95.0           2

In [277]:
# plotando

fig = px.scatter(df_1999_2009_carros,
                x="Autonomia",
                y="Quantidade",
                size="Quantidade",
                title="<b>Figura 6: Relação de autonomia e quantidade registrada 1999- 2009<b>",
                text="Modelo",
                color="Modelo",
                labels={"Autonomia": "Autonomia em Milhas"},
                color_discrete_sequence=px.colors.qualitative.Pastel,
                template="plotly_white")


fig.show()

In [278]:
# Repetindo o processo para 2010 até 2019

df_2010_2019 = df_limpo[(df_limpo["Model Year"] >= 2010) & (df_limpo["Model Year"] <=2019)]

df_2010_2019

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
0,Kitsap,Bainbridge Island,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
1,Kitsap,Port Orchard,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
2,King,Bothell,2011,NISSAN,LEAF,BEV,Eligible,73.0,Puget Sound Energy,15
6,King,Seattle,2016,AUDI,A3,PHEV,Not Eligible (Low Range),16.0,City Of Seattle,10
7,Thurston,Tumwater,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Puget Sound Energy,8
...,...,...,...,...,...,...,...,...,...,...
270423,Skagit,Mount Vernon,2014,TESLA,MODEL S,BEV,Eligible,208.0,Puget Sound Energy,12
270434,Douglas,East Wenatchee,2019,SUBARU,CROSSTREK,PHEV,Not Eligible (Low Range),17.0,Pud No 1 Of Douglas County,7
270441,Pierce,Tacoma,2018,TESLA,MODEL 3,BEV,Eligible,215.0,Bonneville Power Administration,8
270443,Klickitat,Trout Lake,2017,BMW,I3,PHEV,Eligible,97.0,Bonneville Power Administration,9
270445,King,Sammamish,2019,TESLA,MODEL 3,BEV,Eligible,220.0,Puget Sound Energy,7

In [279]:
# Criando uma tabela para os carros de 2010 à 2019, com modelo, autonomia e quantidade.

df_2010_2019_carros = df_2010_2019.groupby(["Make", "Model", "Electric Vehicle Type"]).agg({"Electric Range": "mean", "Model Year": "count"})

df_2010_2019_carros = df_2010_2019_carros.reset_index()

df_2010_2019_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,AUDI,A3,PHEV,16.000000,532
1,AUDI,E-TRON,BEV,204.000000,529
2,AZURE DYNAMICS,TRANSIT CONNECT ELECTRIC,BEV,56.000000,3
3,BMW,330E,PHEV,14.000000,179
4,BMW,530E,PHEV,14.944444,288
...,...,...,...,...,...
57,VOLVO,S60,PHEV,22.000000,9
58,VOLVO,S90,PHEV,21.000000,23
59,VOLVO,XC60,PHEV,17.000000,228
60,VOLVO,XC90,PHEV,15.361111,360
61,WHEEGO ELECTRIC CARS,WHEEGO,PHEV,100.000000,2

In [280]:
# Juntando Marca, nome do modelo e tipo em uma célula só

df_2010_2019_carros["Model"] = df_2010_2019_carros["Make"] + " " + df_2010_2019_carros["Model"] + " " + df_2010_2019_carros["Electric Vehicle Type"]

df_2010_2019_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,AUDI,AUDI A3 PHEV,PHEV,16.000000,532
1,AUDI,AUDI E-TRON BEV,BEV,204.000000,529
2,AZURE DYNAMICS,AZURE DYNAMICS TRANSIT CONNECT ELECTRIC BEV,BEV,56.000000,3
3,BMW,BMW 330E PHEV,PHEV,14.000000,179
4,BMW,BMW 530E PHEV,PHEV,14.944444,288
...,...,...,...,...,...
57,VOLVO,VOLVO S60 PHEV,PHEV,22.000000,9
58,VOLVO,VOLVO S90 PHEV,PHEV,21.000000,23
59,VOLVO,VOLVO XC60 PHEV,PHEV,17.000000,228
60,VOLVO,VOLVO XC90 PHEV,PHEV,15.361111,360
61,WHEEGO ELECTRIC CARS,WHEEGO ELECTRIC CARS WHEEGO PHEV,PHEV,100.000000,2

In [281]:
# Removendo colunas desnecessárias, renomeando colunas e  arredondando a autonomia


df_2010_2019_carros = df_2010_2019_carros.rename(columns={"Model Year": "Quantidade", "Electric Range": "Autonomia", "Model": "Modelo"})

df_2010_2019_carros.drop(columns=["Make", "Electric Vehicle Type"], inplace=True)

df_2010_2019_carros["Autonomia"] = df_2010_2019_carros["Autonomia"].round()

df_2010_2019_carros

                                         Modelo  Autonomia  Quantidade
0                                  AUDI A3 PHEV       16.0         532
1                               AUDI E-TRON BEV      204.0         529
2   AZURE DYNAMICS TRANSIT CONNECT ELECTRIC BEV       56.0           3
3                                 BMW 330E PHEV       14.0         179
4                                 BMW 530E PHEV       15.0         288
..                                          ...        ...         ...
57                               VOLVO S60 PHEV       22.0           9
58                               VOLVO S90 PHEV       21.0          23
59                              VOLVO XC60 PHEV       17.0         228
60                              VOLVO XC90 PHEV       15.0         360
61             WHEEGO ELECTRIC CARS WHEEGO PHEV      100.0           2

[62 rows x 3 columns]

In [282]:
# Novamente plotando

fig = px.scatter(df_2010_2019_carros,
                x="Autonomia",
                y="Quantidade",
                size="Quantidade",
                title="<b>Figura 7: Relação de autonomia e quantidade registrada 2010- 2019<b>",
                color="Modelo",
                labels={"Autonomia": "Autonomia em Milhas"},
                color_discrete_sequence=px.colors.qualitative.Pastel,
                template="plotly_white")


fig.show()

In [283]:
# Começando tudo denovo para 2020 - 2026

df_2020_2026 = df_limpo[(df_limpo["Model Year"] >= 2020) & (df_limpo["Model Year"] <= 2026)]

df_2020_2026.reset_index()

df_2020_2026

,County,City,Model Year,Make,Model,Electric Vehicle Type,CAFV Status,Electric Range,Electric Utility,Vehicle Age
3,Yakima,Selah,2020,CHEVROLET,BOLT EV,BEV,Eligible,259.0,Pacificorp,6
4,King,Seattle,2020,KIA,NIRO,PHEV,Not Eligible (Low Range),26.0,City Of Seattle,6
5,Thurston,Olympia,2023,KIA,NIRO,PHEV,Eligible,33.0,Puget Sound Energy,3
10,Snohomish,Bothell,2024,BMW,X5,PHEV,Eligible,39.0,Puget Sound Energy,2
17,Kitsap,Silverdale,2020,TESLA,MODEL Y,BEV,Eligible,291.0,Puget Sound Energy,6
...,...,...,...,...,...,...,...,...,...,...
270449,Snohomish,Woodinville,2023,TESLA,MODEL 3,BEV,NaN,NaN,Puget Sound Energy,3
270450,Skagit,Burlington,2024,RIVIAN,EDV,BEV,NaN,NaN,Puget Sound Energy,2
270451,Clark,Vancouver,2024,HONDA,PROLOGUE,BEV,NaN,NaN,Bonneville Power Administration,2
270452,Pierce,Tacoma,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,Bonneville Power Administration,3
270453,King,Seattle,2023,JEEP,WRANGLER,PHEV,Not Eligible (Low Range),21.0,City Of Seattle,3

In [284]:
# Repetindo a unificação

df_2020_2026_carros = df_2020_2026.groupby(["Make", "Model", "Electric Vehicle Type"]).agg({"Electric Range": "mean", "Model Year": "count"})

df_2020_2026_carros = df_2020_2026_carros.reset_index()

df_2020_2026_carros

           Make   Model Electric Vehicle Type  Electric Range  Model Year
0         ACURA     ZDX                   BEV             NaN         355
1    ALFA ROMEO  TONALE                  PHEV       33.000000          98
2          AUDI      A6                   BEV             NaN          51
3          AUDI    A7 E                  PHEV       24.000000          11
4          AUDI    A8 E                  PHEV       17.000000           4
..          ...     ...                   ...             ...         ...
154       VOLVO     S90                  PHEV       35.000000          17
155       VOLVO     V60                  PHEV       39.100000         100
156       VOLVO    XC40                   BEV             NaN        1388
157       VOLVO    XC60                  PHEV       30.424608        1658
158       VOLVO    XC90                  PHEV       27.677062        1988

[159 rows x 5 columns]

In [285]:
# Jutando informações novamente

df_2020_2026_carros["Model"] = df_2020_2026_carros["Make"] + " " + df_2020_2026_carros["Model"] + " " + df_2020_2026_carros["Electric Vehicle Type"]

df_2020_2026_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
0,ACURA,ACURA ZDX BEV,BEV,NaN,355
1,ALFA ROMEO,ALFA ROMEO TONALE PHEV,PHEV,33.000000,98
2,AUDI,AUDI A6 BEV,BEV,NaN,51
3,AUDI,AUDI A7 E PHEV,PHEV,24.000000,11
4,AUDI,AUDI A8 E PHEV,PHEV,17.000000,4
...,...,...,...,...,...
154,VOLVO,VOLVO S90 PHEV,PHEV,35.000000,17
155,VOLVO,VOLVO V60 PHEV,PHEV,39.100000,100
156,VOLVO,VOLVO XC40 BEV,BEV,NaN,1388
157,VOLVO,VOLVO XC60 PHEV,PHEV,30.424608,1658
158,VOLVO,VOLVO XC90 PHEV,PHEV,27.677062,1988

### Surgem NaNs!

Como citado antes, alguns carros não tem sua autonomia registrada e constam como valores NaNs, como em um gráfico eles são ignorados, decidi por remover eles.

In [286]:
# Removendo NaNs

df_2020_2026_carros = df_2020_2026_carros.dropna(subset=["Electric Range"])

df_2020_2026_carros

,Make,Model,Electric Vehicle Type,Electric Range,Model Year
1,ALFA ROMEO,ALFA ROMEO TONALE PHEV,PHEV,33.000000,98
3,AUDI,AUDI A7 E PHEV,PHEV,24.000000,11
4,AUDI,AUDI A8 E PHEV,PHEV,17.000000,4
5,AUDI,AUDI E-TRON BEV,BEV,222.000000,678
7,AUDI,AUDI E-TRON SPORTBACK BEV,BEV,218.000000,208
...,...,...,...,...,...
153,VOLVO,VOLVO S60 PHEV,PHEV,32.857143,196
154,VOLVO,VOLVO S90 PHEV,PHEV,35.000000,17
155,VOLVO,VOLVO V60 PHEV,PHEV,39.100000,100
157,VOLVO,VOLVO XC60 PHEV,PHEV,30.424608,1658
158,VOLVO,VOLVO XC90 PHEV,PHEV,27.677062,1988

In [287]:
# removendo as colunas inúteis e arredondando a autonomia

df_2020_2026_carros = df_2020_2026_carros.drop(columns=["Make", "Electric Vehicle Type"])

df_2020_2026_carros["Electric Range"] = df_2020_2026_carros["Electric Range"].round()

df_2020_2026_carros.reset_index()

df_2020_2026_carros

                         Model  Electric Range  Model Year
1       ALFA ROMEO TONALE PHEV            33.0          98
3               AUDI A7 E PHEV            24.0          11
4               AUDI A8 E PHEV            17.0           4
5              AUDI E-TRON BEV           222.0         678
7    AUDI E-TRON SPORTBACK BEV           218.0         208
..                         ...             ...         ...
153             VOLVO S60 PHEV            33.0         196
154             VOLVO S90 PHEV            35.0          17
155             VOLVO V60 PHEV            39.0         100
157            VOLVO XC60 PHEV            30.0        1658
158            VOLVO XC90 PHEV            28.0        1988

[79 rows x 3 columns]

In [288]:
# Renomeando as colunas

df_2020_2026_carros = df_2020_2026_carros.rename(columns={"Model": "Modelo", "Electric Range": "Autonomia", "Model Year": "Quantidade"})

df_2020_2026_carros

                        Modelo  Autonomia  Quantidade
1       ALFA ROMEO TONALE PHEV       33.0          98
3               AUDI A7 E PHEV       24.0          11
4               AUDI A8 E PHEV       17.0           4
5              AUDI E-TRON BEV      222.0         678
7    AUDI E-TRON SPORTBACK BEV      218.0         208
..                         ...        ...         ...
153             VOLVO S60 PHEV       33.0         196
154             VOLVO S90 PHEV       35.0          17
155             VOLVO V60 PHEV       39.0         100
157            VOLVO XC60 PHEV       30.0        1658
158            VOLVO XC90 PHEV       28.0        1988

[79 rows x 3 columns]

In [291]:
# Plotando

fig = px.scatter(df_2020_2026_carros,
                x="Quantidade",
                y="Autonomia",
                size="Quantidade",
                title="<b>Figura 7: Relação de autonomia e quantidade registrada 2020- 2026<b>",
                color="Modelo",
                labels={"Autonomia": "Autonomia em Milhas"},
                color_discrete_sequence=px.colors.qualitative.Pastel,
                template="plotly_white")

fig.show()